/*
 * @copyright (c) 2008, Hedspi, Hanoi University of Technology
 * @author Huu-Duc Nguyen
 * @version 1.0
 */

#include "charcode.h"

/*
 * Bảng charCodes dùng để ánh xạ mỗi mã ASCII (0–255)
 * sang một loại ký tự (CharCode).
 *
 * Mục đích:
 *  - Giúp lexer nhanh chóng xác định loại ký tự bằng cách tra cứu O(1)
 *  - Không cần kiểm tra ký tự bằng nhiều câu lệnh if/else
 *
 * Ví dụ:
 *  charCodes['A'] → CHAR_LETTER
 *  charCodes['9'] → CHAR_DIGIT
 *  charCodes['+'] → CHAR_PLUS
 *  charCodes[' '] → CHAR_SPACE
 *  charCodes['?'] → CHAR_UNKNOWN (vì không định nghĩa)
 *
 * Cấu trúc:
 *  - Mỗi dòng gồm 8 giá trị (8 ký tự ASCII)
 *  - Các ký tự không dùng hoặc không nhận diện được → CHAR_UNKNOWN
 */

CharCode charCodes[256] = {
    /* 0–15: Các mã điều khiển ASCII (NUL, SOH, …) → UNKNOWN */
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_SPACE, /* '\t' */
    CHAR_SPACE,               /* '\n' */
    CHAR_SPACE,               /* '\v' */
    CHAR_SPACE,               /* '\f' */
    CHAR_SPACE,               /* '\r' */
    CHAR_UNKNOWN, CHAR_UNKNOWN,

    /* 16–31: Các mã điều khiển tiếp theo → UNKNOWN */
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,

    /* 32–47: ký tự đặc biệt */
    CHAR_SPACE,        // ' ' (space)
    CHAR_EXCLAIMATION, // '!'
    CHAR_UNKNOWN,      // '"'
    CHAR_UNKNOWN,      // '#'
    CHAR_UNKNOWN,      // '$'
    CHAR_UNKNOWN,      // '%'
    CHAR_UNKNOWN,      // '&'
    CHAR_SINGLEQUOTE,  // '\''
    CHAR_LPAR,         // '('
    CHAR_RPAR,         // ')'
    CHAR_TIMES,        // '*'
    CHAR_PLUS,         // '+'
    CHAR_COMMA,        // ','
    CHAR_MINUS,        // '-'
    CHAR_PERIOD,       // '.'
    CHAR_SLASH,        // '/'

    /* 48–57: '0'–'9' → DIGIT */
    CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT,
    CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT, CHAR_DIGIT,
    CHAR_DIGIT, CHAR_DIGIT,

    CHAR_COLON,     // ':'
    CHAR_SEMICOLON, // ';'
    CHAR_LT,        // '<'
    CHAR_EQ,        // '='
    CHAR_GT,        // '>'
    CHAR_UNKNOWN,   // '?'

    /* 64–90: 'A'–'Z' → LETTER */
    CHAR_UNKNOWN, // '@'
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_LETTER, // 'Z'
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,

    /* 97–122: 'a'–'z' → LETTER (tương tự A–Z) */
    CHAR_UNKNOWN,
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER, CHAR_LETTER,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,

    /* 128–255: Mặc định là UNKNOWN (ASCII mở rộng không dùng) */
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,

    /* 160–191 */
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,

    /* 192–223 */
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,

    /* 224–255 */
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN,
    CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN, CHAR_UNKNOWN};
